### ISSUE TITLE
Addon repository not recognized on HASSIO  2023.6.3/Supervisor 2023.06.2 https://github.com/Akulatraxas/ha-modbusproxy

### ISSUE THREAD

**Issue by gody01** [Akulatraxas/ha-modbusproxy#17]
Hello,

I'm trying to setup modbus proxy on hassio.
After adding repository to add-ons, no store is recognized for Modbus Proxy.
It seems, that repository is installed:

![Zaslonska slika 2023-06-24 22-06-41](https://github.com/Akulatraxas/ha-modbusproxy/assets/3974636/78cb63bd-0820-4e60-b0e3-9a6a8eddbdff)

**Comment by Akulatraxas** [comment]
Do you still have an issue? You seem to have successfully installed the repo?
