### ISSUE TITLE
Configuration question - modbus-proxy + SolarEdge Modbus integration

### ISSUE THREAD

**Issue by ChristophCaina** [Akulatraxas/ha-modbusproxy#2]
Hi,
maybe, you can help me a bit with a setup-question:

In the solaredge_modbus integration, I can see, that the connection is configured for Modbus Port 1502
```
"domain": "solaredge_modbus",
                "title": "solaredge",
                "data": {
                    "name": "solaredge",
                    "port": 1502,
                    "read_meter_1": true,
                    "read_meter_2": false,
                    "read_meter_3": false,
                    "read_battery_1": false,
                    "read_battery_2": false,
                    "scan_interval": 30,
                    "host": "192.168.52.247"
                },
                "options": {},
                "pref_disable_new_entities": false,
                "pref_disable_polling": false,
                "source": "user",
                "unique_id": "192.168.52.247",
                "disabled_by": null
```

In my Wallbox, it seems that the default-Port 502 has been taken.
Now, I am a bit confused, because several Screenshots from the Modbus-Configuration on the Inverter are also showing the Port 1502 on SolarEdge...

Within the Documentation, I cann see two information blocks - one, where the Port 1502 has been mentioned as default port, and one with default port 502
![grafik](https://user-images.githubusercontent.com/26391061/170469262-437b741c-e431-4a46-8e16-ab66f662c21a.png)
![grafik](https://user-images.githubusercontent.com/26391061/170469288-39afe9e8-1f3b-4b1a-955a-7c9abed999c4.png)

Now, I am a bit confused, if my SolarEdge_Modbus Integration would work, when I keep the default configuration in your ha_modbusproxy...

Or do I need to change the configuration for the solaredge_modbus integration to port 502, just the same as the Wallbox is using?
(that I need to change the IP address - that's pretty clear... :) )

Thanks a lot!

**Comment by ChristophCaina** [comment]
can be closed.
It seems, that SolarEdge can work with both ports...

**Comment by Akulatraxas** [comment]
The port itself is not important and can be the same on all devices but its not a requirement. Personally id recommend letting everything run at the modbus standard port of 502 because thats the officially registered port :)
