### ISSUE TITLE
The modebusproxy addon no longer works.

### ISSUE THREAD

**Issue by Vaszago** [Akulatraxas/ha-modbusproxy#20]
The problem is likely that the base image of the container now disallows using pip without venv. 

Can you please fix the error.

Thanks

Describe the issue you are experiencing
The addon can no longer be installed and this error message appears.

23-12-19 14:38:35 INFO (MainThread) [supervisor.docker.addon] Starting build for 81ab01ea/amd64-addon-modbus_proxy:1.0.15
23-12-19 14:38:38 ERROR (MainThread) [supervisor.docker.addon] Can't build 81ab01ea/amd64-addon-modbus_proxy:1.0.15: The command '/bin/ash -o pipefail -c pip install modbus-proxy' returned a non-zero code: 1
23-12-19 14:38:38 ERROR (MainThread) [supervisor.docker.addon] Build log:
Step 1/16 : ARG BUILD_FROM

Step 2/16 : FROM $BUILD_FROM

---> 75c2208b90c6

Step 3/16 : RUN apk add --no-cache python3 py3-pip py3-yaml

---> Using cache

---> 00cb6e652b92

Step 4/16 : RUN pip install modbus-proxy

---> Running in d08bd459b055

error: externally-managed-environment

× This environment is externally managed
╰─>
The system-wide python installation should be maintained using the system
package manager (apk) only.

If the package in question is not packaged already (and hence installable via
"apk add py3-somepackage"), please consider installing it inside a virtual
environment, e.g.:

python3 -m venv /path/to/venv
. /path/to/venv/bin/activate
pip install mypackage

To exit the virtual environment, run:

deactivate

The virtual environment is not deleted, and can be re-entered by re-sourcing
the activate file.

To automatically manage virtual environments, consider using pipx (from the
pipx package).
note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.

Removing intermediate container d08bd459b055

**Comment by Akulatraxas** [comment]
i was not able to fix it today but ill have a look tomorrow!

**Comment by Vaszago** [comment]
👍

**Comment by Akulatraxas** [comment]
It was very weird to reproduce. While i could reproduce it in the devcontainer when i try to actually debug it by building the image like mentioned here (https://developers.home-assistant.io/docs/add-ons/testing/) its just runs and its happy. 

Anyway, new version (1.16) fixes the problem
https://github.com/Akulatraxas/ha-modbusproxy/pull/21

**Comment by Vaszago** [comment]
Thanks.
Can install the app. But it ends again after starting.
See log. Can't find a folder.

![image](https://github.com/Akulatraxas/ha-modbusproxy/assets/66181893/5e00e001-f1ba-4f38-91db-4a08b17f9937)

**Comment by Al3xand3r1987** [comment]
> Thanks. Can install the app. But it ends again after starting. See log. Can't find a folder.
> 
> ![image](https://private-user-images.githubusercontent.com/66181893/292384045-5e00e001-f1ba-4f38-91db-4a08b17f9937.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMzgyNzgsIm5iZiI6MTcwMzIzNzk3OCwicGF0aCI6Ii82NjE4MTg5My8yOTIzODQwNDUtNWUwMGUwMDEtZjFiYS00ZjM4LTkxZGItNGEwOGIxN2Y5OTM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDA5MzkzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5ZjZmZTc4MTMyOTdmM2I0ZGVkZjZhY2U3ZDE1OWQ1Njk0Y2VhYmM1ZGI4MmI3MTQ2YTRjYTY2MDVmNWU1Y2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EjTD50rErCwHMrCmIsIK6xGW0lZBFfCkTLZNDIf0lug)

I also have the same problem. The latest update for Modbus Proxy didn't help either

**Comment by Maikel-K** [comment]
When trying to install version 1.0.18 i get this error message:
Failed to install add-on
The command '/bin/ash -o pipefail -c apk add --no-cache python3 py3-pip py3-yaml' returned a non-zero code: 3

HA information:

Core           2024.1.4
Supervisor 2023.12.1
Operating System
Frontend    20240104.0
