### ISSUE TITLE
Can't start version 1.0.6  (22.12.2023)

### ISSUE THREAD

**Issue by timostr** [Akulatraxas/ha-modbusproxy#22]
Version 1.0.16   from 22.12.2023 refuses to start:
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
Preparing to run modbus-proxy
Upstream: 192.168.188.56:1502
Listen: 8887
Timeout: 60
Connection Time: 2.0
Loglevel: INFO
Generated Config
devices:
  - modbus:
      url: 192.168.188.56:1502 # device url (mandatory)
      timeout: 60 # communication timeout (s) (optional, default: 10)
      connection_time: 2.0 # delay after connection (s) (optional, default: 0)
    listen:
      bind: 0:8887 # listening address (mandatory)
logging:
  version: 1
  formatters:
    standard:
      format: "%(asctime)s %(levelname)8s %(name)s: %(message)s"
  handlers:
    console:
      class: logging.StreamHandler
      formatter: standard
  root:
    handlers: ['console']
    level: INFO
/run.sh: line 29: ./venv/bin/activate: No such file or directory
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by Vaszago** [comment]
I have the same error. Can't start

![image](https://github.com/Akulatraxas/ha-modbusproxy/assets/66181893/088e0074-40e2-4bd4-9ce3-3d3010ad8bec)

**Comment by jerhaag** [comment]
Same issue. Add-on does not start:

/run.sh: line 29: ./venv/bin/activate: No such file or directory

**Comment by Schlichi83** [comment]
I have the same problem. Shouldn‘t have updated :-(

**Comment by faithless11** [comment]
Yes same Problem here... 
/run.sh: line 29: ./venv/bin/activate: No such file or directory

**Comment by abard35** [comment]
Same issue

**Comment by requiemmg** [comment]
Add me to the list...

**Comment by daklemo** [comment]
Welcome to the club...
... same problem here

**Comment by Uhae** [comment]
Same problem here. Is there an easy way to roll back to 1.0.5?

**Comment by ManfredGiesinger** [comment]
Same problem here with 1.0.16, 
- restored 1.0.15, which works for me

**Comment by Schlichi83** [comment]
> Same problem here with 1.0.16,
> 
> * restored 1.0.15, which works for me

How did you manage to restore?

**Comment by Uhae** [comment]
I also just restored and it works fine. Settings -> System -> Backups and then choose the backup you created while updating (in my case: addon_bc3b947b_modbus_proxy_1.0.15

**Comment by abard35** [comment]
![image](https://github.com/Akulatraxas/ha-modbusproxy/assets/97988225/406a2b38-9c36-4426-a6ff-9a43279d6ce3)


> > Same problem here with 1.0.16,
> > 
> > * restored 1.0.15, which works for me
> 
> How did you manage to restore?

![image](https://github.com/Akulatraxas/ha-modbusproxy/assets/97988225/17057a4a-bc00-49da-92c1-66f013d4b0e7)

**Comment by Schlichi83** [comment]
Thank you - worked like a charm! :-)

**Comment by Vaszago** [comment]
The problem is that version 1.15 cannot be installed for me.

**Comment by MrMontesa** [comment]
Same issue.
restored backup as workaround. keep in mind to untick the "enable automatic updates" for now.

**Comment by Akulatraxas** [comment]
Oh sorry, i did not expect that the base container of the addon does not get rebuilded but it uses the run of the new version.
1.18 will arrive soon that should fix the problem. Hit the "rebuild" button after update if the error persists.

**Comment by turbolooser** [comment]
1.017 + rebuild error still persist.
reverting back to 1.015

**Comment by Vaszago** [comment]
Now another mistake

![image](https://github.com/Akulatraxas/ha-modbusproxy/assets/66181893/92d58a9e-07f3-4e2a-bb0d-9baffaff9d62)

**Comment by Akulatraxas** [comment]
Wait for the 1.0.18 to show up, then update.
If the error persists hit the Rebuild button.

**Comment by Vaszago** [comment]
Thanks, problem solved. Works perfectly again.

**Comment by daklemo** [comment]
Confirm: 1.0.18 fixed the problem

**Comment by abard35** [comment]
Works again. Thanks
