### ISSUE TITLE
Can't install add-on

### ISSUE THREAD

**Issue by Maikel-K** [Akulatraxas/ha-modbusproxy#23]
Hi,

Im getting this error:
Failed to install add-on
The command '/bin/ash -o pipefail -c apk add --no-cache python3 py3-pip py3-yaml' returned a non-zero code: 3

I think the line should be /bin/bash ???

**Comment by Akulatraxas** [comment]
No, ash is the default shell of alpine which is the base for the container. 
Does your instance has full internet access ?  If so then I’d recommend to retry :)

**Comment by Maikel-K** [comment]
It should have full internet, if not it would fail?

How can I check if it has full internet access?

**Comment by Akulatraxas** [comment]
@Maikel-K 
I have not heard from anyone else having problems at the moment. Is your issue gone as well ?

**Comment by Maikel-K** [comment]
Hi,

I just installed Home Assistant in Proxmox and restored my backup. Now i can install your addon without problems!
Thanks for that!
