### ISSUE TITLE
error after starting the Addon

### ISSUE THREAD

**Issue by ChristophCaina** [Akulatraxas/ha-modbusproxy#3]
Hi,
After starting the Addon, I'll get the following error:
```
s6-overlay-suexec: fatal: can only run as pid 1
```

**Comment by ChristophCaina** [comment]
this seems to be related to this topic at HomeAssistant:

https://community.home-assistant.io/t/hello-world-example-addon-from-developer-docs-stopped-working-s6-overlay-issue/421486/2

**Comment by Akulatraxas** [comment]
Thank you for reporting and even providing a PR! :)
