### ISSUE TITLE
Missing configuration "connection_time"

### ISSUE THREAD

**Issue by Dark-Tower-Coder** [Akulatraxas/ha-modbusproxy#8]
Hey
I'm currently using a modbus-proxy on another system in a docker container.
Unfortunately, this connection is not 100% stable, which is why I want to test your implementation.

Unfortunately, I don't have the option to set "connection_time".
The default seems to be "connection_time: 0.1". But I need "connection_time: 2".
Background:
I connect the modbus-proxy to my SUN2000 and it needs the mentioned option.

Can you tell me where I can adjust it manually?

If possible, please also provide this setting via the GUI.

Many Thanks :-)
Greeting
Tower

**Comment by scrichab** [comment]
i'm also looking for that setup
i tied to setup in yaml but won't work

**Comment by thomasnas** [comment]
Hi,
Thanks for your effort in making this integration.
I have the Huawei Sun2000 inverter as well here at home and would like this integration to provide modbus connections to both my HA system as well as another system.
For the moment I can't get the home-assistant to connect to the modbus-proxy.
Does it need the connection_time setting ?
Would you be able to tell me if you were able to work on it ?
Thanks in advance

**Comment by Akulatraxas** [comment]
@thomasnas i think you have another issue, please open another ticket in here to keep things seperate :) 

@scrichab i am currently testing a new version including timeout and connection_time config as well as some changed logging, will be hit the repo soon

**Comment by Dark-Tower-Coder** [comment]
With this new option, I was able to easily connect and use my Huawei SUN2000.

Thank you for the integration :-)
